name: 'Draft PR Closer'
description: 'Automatically close draft PRs after a period of time'
branding:
  icon: x
  color: red
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  days-before-close:
    description: 'Number of days before closed'
    required: true
  closing-comment:
    description: 'Comment to add to PR when closing'
runs:
  using: 'node12'
  main: 'dist/index.js'
